Zqs 870/track backend usage
zapatacomputing/z-quantum-core pull request #446
Opened 2021-11-29 22:04 UTC by AthenaCaesura

Created MeasurementTrackingBackend class which allows one to keep track of all the measurement data collected in an experiment in an external json file. Namely, we keep track of num_shots, bitstrings, counts for each measurement outcome, the implemented circuit, and the number of gates.

This generalized code written for the bp project which only tracked backends for qiskit. This code expands the scope to any type of backend.

The measurement tracking backend class is triggered when the user puts the flag "track_backend_usage" : True in the workflow. The class wraps around an inner_backend and writes all the results of measurements to "raw_measurement_data.json" after each experiment. 

Testing for measurement tracking backend to be added in an upcoming story.

2021-11-30 15:03 UTC, mstechly requested changes

2021-11-30 18:11 UTC, AthenaCaesura commented on .coveragerc
> -# .coveragerc to control coverage.py
I found another copy of .coveragerc in the main branch and put an identical file in my branch. Hope that's ok.

2021-11-30 18:38 UTC, AthenaCaesura commented on src/python/zquantum/core/trackers.py
> +            circuit (Circuit): Implemented circuit.
Done. :)

2021-11-30 18:39 UTC, AthenaCaesura commented on src/python/zquantum/core/trackers.py
> +    To enable tracking, simply put the key-value pair "track_measurements" : True
I put the comment in the docstring of all of the methods in steps where MeasurementTrackingBackend could be called. If methods have no docstrings, I just put the comment in the module docstring (i.e. `measurements.py`).

2021-12-01 10:30 UTC, alexjuda reviewed
I've added a few questions/suggestions :) 

Side question: we still have ["acceptance tests"](https://github.com/zapatacomputing/z-quantum-core/tree/main/tests/acceptance_tests) that only contain tests for out steps. Wanna add tests for backend tracker there, too?

2021-12-01 10:30 UTC, alexjuda commented on src/python/zquantum/core/trackers.py
> +        rename(self.file_name, "raw-measurement-data.json")
Do I understand correctly that the motivation for this method was to let the user to store the data under a different file name? WDYT about removing this method and allowing the user to pass a file object to `save_raw_measurement_data`?

2021-12-01 10:30 UTC, alexjuda commented on steps/evaluation.py
> +
Shouldn't this follow invocation of `backend.save_raw_measurement_data()`? If so, can you help me find it?

Note that this comment will be out of date if you decide to merge `save...` and `rename...` methods.

2021-12-01 10:30 UTC, alexjuda commented on tests/zquantum/core/trackers_test.py
> +        backend.run_circuit_and_measure(circuit, n_samples=1000)
If we can pass `n_samples` to `run_circuit_and_measure`, what's the reason to mutate the backend on line above it?

2021-12-01 10:30 UTC, alexjuda commented on tests/zquantum/core/trackers_test.py
> +        f = open(backend.file_name)
1. If you don't wrap `open(...)` in a context manager you're responsible for closing the file pointer on your own. I can't see the `f.close()` in this test, so I'd expect FS errors due to removal of an dangling/opened file at the test cleanup. Is there a reason not to use `with open(...) as f`?
2. If this test fails for some reason we end up with temporary files cluttering the current PWD. WDYT about using a [tempfile]()https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) or a [tempdir](https://docs.python.org/3/library/tempfile.html#tempfile.TemporaryDirectory)? You can see how we use that in [SDK's tests](https://github.com/zapatacomputing/orquestra-sdk/blob/a9b2f1d94d0f7671c7bbb357acfde1ffb8dbb9ba/tests/v2/test_dispatch.py#L10-L46)

2021-12-01 18:27 UTC, mstechly commented
@alexjuda regarding acceptance tests – I don't think it's necessary. Since we'll be deleting them in near future, I don't think it's worth spending time on them.

2021-12-01 23:05 UTC, mstechly approved these changes
Looks good to me!
Just please add `.coveragerc` again ;)
Waiting for approval from @alexjuda

2021-12-02 14:36 UTC, merged