Faster custom gates
zapatacomputing/z-quantum-core pull request #472
Opened 2022-03-29 09:36 UTC by MSRudolph

After discussing my use case with @AthenaCaesura, she suggested I try using my custom operations with `numpy.ndarrays` rather than `sympy.Matrix`. This alone reduces the runtime of my specific algorithm by an order of magnitude. I was able to cut the remaining run time more than in half by implementing a quicker bit flip operation. These changes made my application about ~40x faster.

2022-03-31 13:09 UTC, AthenaCaesura approved these changes

2022-04-15 18:25 UTC, dexter2206 requested changes
Looks good, but there is a test case missing for one of the added features.

2022-04-15 18:25 UTC, dexter2206 commented on src/python/zquantum/core/circuits/_gates.py
> +            return self.matrix
Line 361 is not covered. I suggest adding a test case for using `CustomGateMatrixFactory` with numpy array in place of sympy matrix.

2022-04-19 14:05 UTC, AthenaCaesura commented
Closing this PR as we have already moved over the the code from `z-quantum-core` to `orquestra-quantum` so it doesn't mkae sense to keep adding features to core. However, I am not closing this branch as it will be helpful in the future when making this update to `orquestra-quantum`.

2022-04-19 14:05 UTC, closed without merging