Adding function to convert Pauli terms in qubit operator to circuits
zapatacomputing/z-quantum-core pull request #86
Opened 2020-09-02 19:14 UTC by pediejo

2020-11-03 15:25 UTC, simonwa7 requested changes

2020-11-03 15:25 UTC, simonwa7 commented on src/python/zquantum/core/circuit/_gate.py
> +            return [qiskit.extensions.standard.CnotGate(), [qiskit_qubits[0], qiskit_qubits[1]], []]
This is repeated from line 522

2020-11-03 15:25 UTC, simonwa7 commented on src/python/zquantum/core/circuit/_gate.py
> +            return [qiskit.extensions.standard.SwapGate(), [qiskit_qubits[0], qiskit_qubits[1]], []]
I believe these still need to be tested

2020-11-03 15:25 UTC, simonwa7 commented on src/python/zquantum/core/circuit/_gate.py
> +            ]
Also needs to be tested

2020-11-03 15:25 UTC, simonwa7 commented on src/python/zquantum/core/utils.py
> +    dictionary_stored['dict'] = dictionary
This seems a bit odd - why not just put `'schema'` as one of the keys in the original dict? Pinging @mstechly for input

2020-12-18 21:56 UTC, pediejo commented
This pull request has been superseded by https://github.com/zapatacomputing/z-quantum-core/pull/138. So I am closing it. @akataba, if those early commits of yours on this branch are no longer needed, then we should delete this branch.

2020-12-18 21:56 UTC, closed without merging